jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # Install backend dependencies
      - name: Install Backend
        working-directory: ./backend
        run: npm install

      # Install frontend dependencies
      - name: Install Frontend
        working-directory: ./frontend
        run: npm install

      # Run backend build or start
      - name: Build Backend
        working-directory: ./backend
        run: npm run build

      # Run frontend build
      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build
        
